// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models
{
    /// <summary>Represents the caching strategy for the block device.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Drive_cache_type
    {
        [EnumMember(Value = "Unsafe")]
        #pragma warning disable CS1591
        Unsafe,
        #pragma warning restore CS1591
        [EnumMember(Value = "Writeback")]
        #pragma warning disable CS1591
        Writeback,
        #pragma warning restore CS1591
    }
}
