// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models
{
    /// <summary>Type of the IO engine used by the device. &quot;Async&quot; is supported on host kernels newer than 5.10.51. This field is optional for virtio-block config and should be omitted for vhost-user-block configuration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum Drive_io_engine
    {
        [EnumMember(Value = "Sync")]
        #pragma warning disable CS1591
        Sync,
        #pragma warning restore CS1591
        [EnumMember(Value = "Async")]
        #pragma warning disable CS1591
        Async,
        #pragma warning restore CS1591
    }
}
