// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models
{
    /// <summary>Set the level. The possible values are case-insensitive.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum Logger_level
    {
        [EnumMember(Value = "Error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "Warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "Info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "Debug")]
        #pragma warning disable CS1591
        Debug,
        #pragma warning restore CS1591
        [EnumMember(Value = "Trace")]
        #pragma warning disable CS1591
        Trace,
        #pragma warning restore CS1591
        [EnumMember(Value = "Off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
    }
}
