// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models {
    /// <summary>Which huge pages configuration (if any) should be used to back guest memory.</summary>
    public enum MachineConfiguration_huge_pages
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "2M")]
        #pragma warning disable CS1591
        TwoM,
        #pragma warning restore CS1591
    }
}
