// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models {
    public enum MemoryBackend_backend_type {
        [EnumMember(Value = "File")]
        File,
        [EnumMember(Value = "Uffd")]
        Uffd,
    }
}
