// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models
{
    /// <summary>Enumeration indicating the MMDS version to be configured.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MmdsConfig_version
    {
        [EnumMember(Value = "V1")]
        #pragma warning disable CS1591
        V1,
        #pragma warning restore CS1591
        [EnumMember(Value = "V2")]
        #pragma warning disable CS1591
        V2,
        #pragma warning restore CS1591
    }
}
