// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum Vm_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Paused")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "Resumed")]
        #pragma warning disable CS1591
        Resumed,
        #pragma warning restore CS1591
    }
}
