// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Firecracker.Management.Models {
    public enum Vm_state {
        [EnumMember(Value = "Paused")]
        Paused,
        [EnumMember(Value = "Resumed")]
        Resumed,
    }
}
